version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - hosts:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs
      - /user/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  ssl-generator:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  portainer:
    image: portainer/portainer-ce:2.11.1
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      - VIRTUAL_HOST={url}
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST={url}

volumes:
  portainer_data:
  certs:
  hosts:
