version: '3.8'
services:

  portainer:
    image: portainer/portainer-ce:2.18.2
    container_name: "portainer"
    privileged: true
    volumes:
      - './data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: unless-stopped

networks:
  default:
    external: true
    name: spook
